/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_Personen = 2,
  sym_ingredients_header = 3,
  anon_sym_DASH = 4,
  anon_sym_SPACE = 5,
  sym_preparation_header = 6,
  anon_sym_DOT = 7,
  sym_integer = 8,
  sym_float = 9,
  sym_unit = 10,
  aux_sym_ingredient_name_token1 = 11,
  sym_source_file = 12,
  sym_persons_line = 13,
  sym_ingredients_section = 14,
  sym_ingredient_line = 15,
  sym_preparation_section = 16,
  sym_step_line = 17,
  sym_quantity = 18,
  sym_ingredient_name = 19,
  sym_text = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_ingredients_section_repeat1 = 22,
  aux_sym_preparation_section_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_Personen] = " Personen",
  [sym_ingredients_header] = "ingredients_header",
  [anon_sym_DASH] = "- ",
  [anon_sym_SPACE] = " ",
  [sym_preparation_header] = "preparation_header",
  [anon_sym_DOT] = ". ",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_unit] = "unit",
  [aux_sym_ingredient_name_token1] = "ingredient_name_token1",
  [sym_source_file] = "source_file",
  [sym_persons_line] = "persons_line",
  [sym_ingredients_section] = "ingredients_section",
  [sym_ingredient_line] = "ingredient_line",
  [sym_preparation_section] = "preparation_section",
  [sym_step_line] = "step_line",
  [sym_quantity] = "quantity",
  [sym_ingredient_name] = "ingredient_name",
  [sym_text] = "text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_ingredients_section_repeat1] = "ingredients_section_repeat1",
  [aux_sym_preparation_section_repeat1] = "preparation_section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_Personen] = anon_sym_Personen,
  [sym_ingredients_header] = sym_ingredients_header,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_preparation_header] = sym_preparation_header,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_unit] = sym_unit,
  [aux_sym_ingredient_name_token1] = aux_sym_ingredient_name_token1,
  [sym_source_file] = sym_source_file,
  [sym_persons_line] = sym_persons_line,
  [sym_ingredients_section] = sym_ingredients_section,
  [sym_ingredient_line] = sym_ingredient_line,
  [sym_preparation_section] = sym_preparation_section,
  [sym_step_line] = sym_step_line,
  [sym_quantity] = sym_quantity,
  [sym_ingredient_name] = sym_ingredient_name,
  [sym_text] = sym_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_ingredients_section_repeat1] = aux_sym_ingredients_section_repeat1,
  [aux_sym_preparation_section_repeat1] = aux_sym_preparation_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Personen] = {
    .visible = true,
    .named = false,
  },
  [sym_ingredients_header] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_preparation_header] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_ingredient_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_persons_line] = {
    .visible = true,
    .named = true,
  },
  [sym_ingredients_section] = {
    .visible = true,
    .named = true,
  },
  [sym_ingredient_line] = {
    .visible = true,
    .named = true,
  },
  [sym_preparation_section] = {
    .visible = true,
    .named = true,
  },
  [sym_step_line] = {
    .visible = true,
    .named = true,
  },
  [sym_quantity] = {
    .visible = true,
    .named = true,
  },
  [sym_ingredient_name] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ingredients_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preparation_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_count = 1,
  field_name = 2,
  field_number = 3,
  field_quantity = 4,
  field_text = 5,
  field_unit = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_count] = "count",
  [field_name] = "name",
  [field_number] = "number",
  [field_quantity] = "quantity",
  [field_text] = "text",
  [field_unit] = "unit",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_count, 0},
  [1] =
    {field_number, 0},
    {field_text, 2},
  [3] =
    {field_name, 5},
    {field_quantity, 1},
    {field_unit, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      if (lookahead == '\t') SKIP(0);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\t') SKIP(2);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == 'P') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '\t') SKIP(2);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 3:
      if (lookahead == '\t') SKIP(3);
      if (lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == 'Z') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'b') ADVANCE(13);
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(39);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 30:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_Personen);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ingredients_header);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_preparation_header);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_unit);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_ingredient_name_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_ingredient_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 32},
  [5] = {.lex_state = 32},
  [6] = {.lex_state = 32},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 32},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 45},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 45},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 30},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_Personen] = ACTIONS(1),
    [sym_ingredients_header] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_preparation_header] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(42),
    [sym_persons_line] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_LF] = ACTIONS(3),
    [sym_integer] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(9), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 4,
      ts_builtin_sym_end,
      sym_ingredients_header,
      sym_preparation_header,
      sym_integer,
  [13] = 4,
    ACTIONS(14), 1,
      sym_integer,
    STATE(3), 1,
      aux_sym_preparation_section_repeat1,
    STATE(35), 1,
      sym_step_line,
    ACTIONS(12), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [27] = 4,
    ACTIONS(19), 1,
      sym_integer,
    STATE(5), 1,
      aux_sym_preparation_section_repeat1,
    STATE(35), 1,
      sym_step_line,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [41] = 4,
    ACTIONS(19), 1,
      sym_integer,
    STATE(3), 1,
      aux_sym_preparation_section_repeat1,
    STATE(35), 1,
      sym_step_line,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [55] = 4,
    ACTIONS(5), 1,
      sym_integer,
    ACTIONS(23), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(43), 1,
      sym_persons_line,
  [68] = 4,
    ACTIONS(25), 1,
      anon_sym_LF,
    ACTIONS(27), 1,
      sym_ingredients_header,
    STATE(8), 1,
      aux_sym_source_file_repeat1,
    STATE(26), 1,
      sym_ingredients_section,
  [81] = 4,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(27), 1,
      sym_ingredients_header,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(25), 1,
      sym_ingredients_section,
  [94] = 4,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(29), 1,
      sym_preparation_header,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(18), 1,
      sym_preparation_section,
  [107] = 4,
    ACTIONS(27), 1,
      sym_ingredients_header,
    ACTIONS(31), 1,
      anon_sym_LF,
    STATE(13), 1,
      aux_sym_source_file_repeat1,
    STATE(25), 1,
      sym_ingredients_section,
  [120] = 4,
    ACTIONS(33), 1,
      anon_sym_LF,
    ACTIONS(35), 1,
      anon_sym_DASH,
    STATE(12), 1,
      aux_sym_ingredients_section_repeat1,
    STATE(38), 1,
      sym_ingredient_line,
  [133] = 4,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_LF,
    STATE(15), 1,
      aux_sym_ingredients_section_repeat1,
    STATE(38), 1,
      sym_ingredient_line,
  [146] = 4,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(27), 1,
      sym_ingredients_header,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(29), 1,
      sym_ingredients_section,
  [159] = 4,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(29), 1,
      sym_preparation_header,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(20), 1,
      sym_preparation_section,
  [172] = 4,
    ACTIONS(39), 1,
      anon_sym_LF,
    ACTIONS(41), 1,
      anon_sym_DASH,
    STATE(15), 1,
      aux_sym_ingredients_section_repeat1,
    STATE(38), 1,
      sym_ingredient_line,
  [185] = 4,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(29), 1,
      sym_preparation_header,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 1,
      sym_preparation_section,
  [198] = 3,
    ACTIONS(44), 1,
      sym_integer,
    ACTIONS(46), 1,
      sym_float,
    STATE(37), 1,
      sym_quantity,
  [208] = 3,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      anon_sym_LF,
    STATE(22), 1,
      aux_sym_source_file_repeat1,
  [218] = 3,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
  [228] = 3,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      anon_sym_LF,
    STATE(23), 1,
      aux_sym_source_file_repeat1,
  [238] = 1,
    ACTIONS(12), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_integer,
  [244] = 3,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
  [254] = 3,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
  [264] = 3,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      anon_sym_LF,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
  [274] = 2,
    ACTIONS(62), 1,
      anon_sym_LF,
    STATE(14), 1,
      aux_sym_source_file_repeat1,
  [281] = 2,
    ACTIONS(64), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
  [288] = 2,
    ACTIONS(66), 1,
      aux_sym_ingredient_name_token1,
    STATE(46), 1,
      sym_text,
  [295] = 1,
    ACTIONS(39), 2,
      anon_sym_LF,
      anon_sym_DASH,
  [300] = 2,
    ACTIONS(68), 1,
      anon_sym_LF,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
  [307] = 2,
    ACTIONS(70), 1,
      aux_sym_ingredient_name_token1,
    STATE(48), 1,
      sym_ingredient_name,
  [314] = 1,
    ACTIONS(72), 1,
      anon_sym_SPACE,
  [318] = 1,
    ACTIONS(74), 1,
      anon_sym_LF,
  [322] = 1,
    ACTIONS(76), 1,
      sym_unit,
  [326] = 1,
    ACTIONS(78), 1,
      anon_sym_DOT,
  [330] = 1,
    ACTIONS(80), 1,
      anon_sym_LF,
  [334] = 1,
    ACTIONS(82), 1,
      anon_sym_SPACE,
  [338] = 1,
    ACTIONS(84), 1,
      anon_sym_SPACE,
  [342] = 1,
    ACTIONS(86), 1,
      anon_sym_LF,
  [346] = 1,
    ACTIONS(88), 1,
      anon_sym_LF,
  [350] = 1,
    ACTIONS(90), 1,
      anon_sym_LF,
  [354] = 1,
    ACTIONS(92), 1,
      anon_sym_LF,
  [358] = 1,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
  [362] = 1,
    ACTIONS(96), 1,
      anon_sym_LF,
  [366] = 1,
    ACTIONS(98), 1,
      anon_sym_Personen,
  [370] = 1,
    ACTIONS(100), 1,
      anon_sym_LF,
  [374] = 1,
    ACTIONS(102), 1,
      anon_sym_LF,
  [378] = 1,
    ACTIONS(104), 1,
      anon_sym_LF,
  [382] = 1,
    ACTIONS(106), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 13,
  [SMALL_STATE(4)] = 27,
  [SMALL_STATE(5)] = 41,
  [SMALL_STATE(6)] = 55,
  [SMALL_STATE(7)] = 68,
  [SMALL_STATE(8)] = 81,
  [SMALL_STATE(9)] = 94,
  [SMALL_STATE(10)] = 107,
  [SMALL_STATE(11)] = 120,
  [SMALL_STATE(12)] = 133,
  [SMALL_STATE(13)] = 146,
  [SMALL_STATE(14)] = 159,
  [SMALL_STATE(15)] = 172,
  [SMALL_STATE(16)] = 185,
  [SMALL_STATE(17)] = 198,
  [SMALL_STATE(18)] = 208,
  [SMALL_STATE(19)] = 218,
  [SMALL_STATE(20)] = 228,
  [SMALL_STATE(21)] = 238,
  [SMALL_STATE(22)] = 244,
  [SMALL_STATE(23)] = 254,
  [SMALL_STATE(24)] = 264,
  [SMALL_STATE(25)] = 274,
  [SMALL_STATE(26)] = 281,
  [SMALL_STATE(27)] = 288,
  [SMALL_STATE(28)] = 295,
  [SMALL_STATE(29)] = 300,
  [SMALL_STATE(30)] = 307,
  [SMALL_STATE(31)] = 314,
  [SMALL_STATE(32)] = 318,
  [SMALL_STATE(33)] = 322,
  [SMALL_STATE(34)] = 326,
  [SMALL_STATE(35)] = 330,
  [SMALL_STATE(36)] = 334,
  [SMALL_STATE(37)] = 338,
  [SMALL_STATE(38)] = 342,
  [SMALL_STATE(39)] = 346,
  [SMALL_STATE(40)] = 350,
  [SMALL_STATE(41)] = 354,
  [SMALL_STATE(42)] = 358,
  [SMALL_STATE(43)] = 362,
  [SMALL_STATE(44)] = 366,
  [SMALL_STATE(45)] = 370,
  [SMALL_STATE(46)] = 374,
  [SMALL_STATE(47)] = 378,
  [SMALL_STATE(48)] = 382,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [9] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [12] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preparation_section_repeat1, 2, 0, 0),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preparation_section_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preparation_section, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preparation_section, 3, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredients_section, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredients_section, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ingredients_section_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ingredients_section_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 8, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 6, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 7, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantity, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_persons_line, 2, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [94] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step_line, 3, 0, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient_name, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient_line, 6, 0, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dish(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dish",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
